services:
  webhook_listener:
    build:
      context: .
      dockerfile: Dockerfile.webhook_listener
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis

  order_dispatcher:
    build:
      context: .
      dockerfile: Dockerfile.order_dispatcher
    restart: always
    depends_on:
      - redis

  cli:
    build:
      context: .
      dockerfile: Dockerfile.cli_process
    restart: always
    stdin_open: true
    tty: true

    depends_on:
      - redis


  redis:
    image: "redis:latest"

