services:
  webhook_listener:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.webhook_listener
    restart: always
    ports:
      - "8005:8000"
    depends_on:
      - redis
    env_file:
      - .staging.env

  order_dispatcher:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.order_dispatcher
    restart: always
    depends_on:
      - redis
    env_file:
      - .staging.env

  cli:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.cli_process
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - redis
    env_file:
      - .staging.env


  redis:
    image: "redis:latest"

