# Dockerfile for cli_process
FROM python:3.10-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential && \
    rm -rf /var/lib/apt/lists/*

run pip install -r requirements.txt

COPY src/ ./src

CMD ["python", "-m", "src.cli_process"]