# Dockerfile for order_dispatcher
FROM python:3.10-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
# Installer les outils de compilation
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential && \
    rm -rf /var/lib/apt/lists/*

run pip install -r requirements.txt
COPY src/ ./src
COPY .env ./src
COPY settings.json .
ENV PYTHONPATH /app/src:$PYTHONPATH
ENV ENV staging

CMD ["python","src/order_dispatcher.py"]